### PR TITLE
Xenial 2.3.10

### PR DESCRIPTION
**Pull request by wdullaer**
Updates the tarball with our performance fix.
Also adds a README with some pointers on how to build the tarball and update this repository.

This PR will create a 2.3.10 debian package once the jenkins job runs.

### CODE REVIEW

**Review by jespada — APPROVED** [review]

**Comment by lord2y** [comment]
As discussed in IRC remove the file `README.md` and you're good to go.

**Comment by wdullaer** [comment]
A pity we can't document this repo :(
I've removed the README

**Review by lord2y — APPROVED** [review]

**Review by exo-cedric — APPROVED** [review]
(trusting you on the content of the tarball :-) )

**Comment by wdullaer** [comment]
We managed to build the debian packages from source directly.
This PR is now replaced by the changes in exoscale/puppetdb#2

After that PR lands, we can probably archive this repository and remove it from jobs.

**Pull request closed without merging**
